<?php
// $Id$
/**
 * @file
 * FileField Meta: Add Video Support to File Field.
 */

function filefield_meta_file_insert($file) {
  filefield_meta($file);
  $record = array_merge(array('fid' => $file->fid), $file->data);
  drupal_write_record('filefield_meta', $record);
}

function filefield_meta_file_update($file) {
  filefield_meta_file_delete($file);
  filefield_meta($file);
  $record = array_merge(array('fid' => $file->fid), $file->data);
  drupal_write_record('filefield_meta', $record);
}

function filefield_meta_file_delete($file) {
  db_query('DELETE FROM {filefield_meta} WHERE fid = %d', $file->fid);
}

function filefield_meta_file_load(&$file) {
  if ($meta = db_fetch_array(db_query('SELECT * FROM {filefield_meta} WHERE fid = %d', $file->fid))) {
    $file->data = is_array($file->data) ? array_merge($meta, $file->data) : $meta;
  }
  else {
    filefield_meta($file);
  }
}

function filefield_meta(&$file) {
  $info = getid3_analyze($file->filepath);
  $file->data['width'] = $file->data['height'] = $file->data['duration'] = 0;
  if (isset($info['video']['resolution_x'])) {
    $file->data['width'] = $info['video']['resolution_x'];
    $file->data['height'] = $info['video']['resolution_y'];
  }
  else if (isset($info['video']['streams'])) {
    foreach($info['video']['streams'] as $stream) {
      $file->data['width'] = max($file->data['width'], $stream['resolution_x']);
      $file->data['height'] = max($file->data['height'], $stream['resolution_y']);
    }
  }
  $file->data['duration'] = $info['playtime_seconds'];
};
